### ISSUE TITLE
«if you visit checkout page and remove all items from cart, there is an 500»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [blushme/checkout#13]
[upwork.com/messages/rooms/room_5a95d6d13f39ee2fa4a43163a7ea6edd/story_8934f348d04efb724e8aad19ba13ab41](https://www.upwork.com/messages/rooms/room_5a95d6d13f39ee2fa4a43163a7ea6edd/story_8934f348d04efb724e8aad19ba13ab41)

**Comment by dmitrii-fediuk** [comment]
Fixed in [1.0.2](https://github.com/blushme/checkout/releases/tag/1.0.2).
